# Generated by Django 3.2.3 on 2021-06-07 20:01

import clothes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fsuser', '0001_initial'),
        ('member', '0001_initial'),
        ('clothes_style', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookbookClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=clothes.models.image_upload_to, verbose_name='룩북 이미지')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록 날짜')),
                ('attributes', models.ManyToManyField(db_column='clothes_attributes', related_name='lookbook_clothes', to='clothes_style.ClothesAttribute', verbose_name='의류 속성')),
                ('category', models.ForeignKey(db_column='clothes_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookbook_clothes', to='clothes_style.clothescategory', verbose_name='의류 카테고리')),
                ('color', models.ForeignKey(db_column='color_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookbook_clothes', to='clothes_style.color', verbose_name='의류 색상')),
                ('member', models.ForeignKey(db_column='member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookbook_clothes', to='member.blackpinkmember', verbose_name='블랙핑크 멤버')),
            ],
            options={
                'verbose_name': '룩북 의류',
                'verbose_name_plural': '룩북 의류',
                'db_table': 'lookbook_clothes',
                'ordering': ['registered_date'],
            },
        ),
        migrations.CreateModel(
            name='UserUploadClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=clothes.models.image_upload_to_with_uuid, verbose_name='사용자 요청 이미지')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='등록 날짜')),
                ('lookbook_clothes', models.ForeignKey(blank=True, db_column='lookbook_clothes_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_upload_clothes', to='clothes.lookbookclothes', verbose_name='룩북 의류')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_upload_clothes', to='fsuser.fsuser', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 요청 의류',
                'verbose_name_plural': '사용자 요청 의류',
                'db_table': 'user_upload_clothes',
                'ordering': ['upload_date'],
            },
        ),
        migrations.CreateModel(
            name='ShopClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='shop-crawling/data.png', upload_to=clothes.models.image_upload_to, verbose_name='쇼핑몰 의류 이미지')),
                ('webpage_url', models.TextField(verbose_name='웹 페이지 URL')),
                ('lookbook_clothes', models.ForeignKey(db_column='lookbook_clothes_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_clothes', to='clothes.lookbookclothes', verbose_name='룩북 의류')),
            ],
            options={
                'verbose_name': '쇼핑몰 의류',
                'verbose_name_plural': '쇼핑몰 의류',
                'db_table': 'shop_clothes',
                'ordering': ['id'],
            },
        ),
    ]
