version: '3.7'

services:
  web:
    build: ./app
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev

  db:
    image: postgres:12.0-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fsuser
      - POSTGRES_PASSWORD=fsblackpink
      - POSTGRES_DB=fashion_scanner
    
volumes:
  postgres_data: