version: '3.7'

services:
  web_prod:
    build: ./app
    container_name: web_prod
    command: gunicorn fashion_scanner.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./.env.prod

  db_prod:
    image: postgres:12.0-alpine
    container_name: db_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data: