# Generated by Django 3.2.3 on 2021-06-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fsuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록 날짜')),
                ('role', models.CharField(choices=[('User', 'User'), ('Staff', 'Staff'), ('Superuser', 'Superuser')], default='User', max_length=10, verbose_name='역할')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'fs_user',
                'ordering': ['registered_date'],
            },
        ),
    ]
