CLOTHES_CATEGORIES_EN_KO = {
    "Anorak": "아노락",
    "Blazer": "블레이저",
    "Blouse": "블라우스",
    "Bomber": "봄버",
    "Button-Down": "와이셔츠",
    "Caftan": "카프탄",
    "Cape": "케이프",
    "Capris": "7부 바지",
    "Cardigan": "가디건",
    "Chinos": "치노",
    "Coat": "코트",
    "Coverup": "커버업",
    "Culottes": "큐롯",
    "Cutoffs": "핫팬츠",
    "Dress": "드레스",
    "Flannel": "프란넬",
    "Gauchos": "가우쵸",
    "Halter": "홀터",
    "Henley": "헨리",
    "Hoodie": "후드티",
    "Jacket": "자켓",
    "Jeans": "청바지",
    "Jeggings": "제깅스",
    "Jersey": "져지",
    "Jodhpurs": "조드푸르",
    "Joggers": "조거스",
    "Jumpsuit": "점프수트",
    "Kaftan": "카프탄",
    "Kimono": "기모노",
    "Leggings": "레깅스",
    "Nightdress": "잠옷",
    "Onesie": "캐주얼 점프슈트",
    "Parka": "파카",
    "Peacoat": "피코트",
    "Poncho": "판초",
    "Robe": "로브",
    "Romper": "롬퍼",
    "Sarong": "사롱",
    "Shirtdress": "셔츠드레스",
    "Shorts": "반바지",
    "Skirt": "치마",
    "Sundress": "선드레스",
    "Sweater": "스웨터",
    "Sweatpants": "츄리닝 바지",
    "Sweatshorts": "츄리닝 반바지",
    "Tank": "나시",
    "Tee": "티셔츠",
    "Top": "탑",
    "Trunks": "트렁크",
    "Turtleneck": "터틀넥",
}

CLOTHES_ATTRIBUTES_EN_KO = {
    "chiffon": "쉬폰",
    "conventional": "클래식",
    "cotton": "면",
    "crew_neckline": "크루넥",
    "denim": "데님",
    "embroidered": "자수",
    "faux": "인조 모피",
    "floral": "꽃무늬",
    "graphic": "프린팅",
    "knit": "니트",
    "lattice": "체크 패턴",
    "leather": "가죽",
    "long_sleeve": "긴팔",
    "loose": "루즈",
    "maxi_length": "긴 기장",
    "mini_length": "짧은 기장",
    "no_dress": "원피스가 아닌",
    "no_neckline": "넥라인 없음",
    "pleated": "플리츠",
    "short_sleeve": "반팔",
    "sleeveless": "나시",
    "solid": "각진",
    "square_neckline": "스퀘어넥",
    "striped": "줄무늬",
    "tight": "타이트",
    "v_neckline": "브이넥",
}
