# Generated by Django 3.2.3 on 2021-05-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name_en', models.CharField(max_length=32)),
                ('attribute_name_kr', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '의류 속성',
                'verbose_name_plural': '의류 속성',
                'db_table': 'clothes_attribute',
            },
        ),
        migrations.CreateModel(
            name='ClothesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_en', models.CharField(max_length=32)),
                ('category_name_kr', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '의류 카테고리',
                'verbose_name_plural': '의류 카테고리',
                'db_table': 'clothes_category',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '색상',
                'verbose_name_plural': '색상',
                'db_table': 'color',
            },
        ),
    ]
